import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        <div className="text-4xl">TODO: Make ME Landing Page</div>
      </main>
    </>
  );
};


export default Home;
