import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Header from '../components/Header';

const Home: NextPage = () => {

  const router = useRouter();
  const session = useSession();

  if (session.data && !session.data?.user?.role) {
    router.push('/welcome');
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        {session.data && <div>Role: {session.data.user?.role}</div>}
      </main>
    </>
  );
};


export default Home;
